name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/caelestis94/telehook/telehook

jobs:
  build-test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test backend in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/apps/api \
            mcr.microsoft.com/dotnet/sdk:9.0 \
            bash -c "dotnet restore TeleHook.Api/TeleHook.Api.csproj && dotnet build TeleHook.Api/TeleHook.Api.csproj --configuration Release && dotnet test TeleHook.Api.Tests/TeleHook.Api.Tests.csproj --configuration Release --verbosity normal"

      - name: Build and test frontend in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/apps/web \
            node:18-alpine \
            sh -c "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm build && pnpm test --passWithNoTests"

  docker-build-push:
    needs: [build-test]
    runs-on: [self-hosted, Linux, X64]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push combined image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "## 🚀 Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "### TeleHook Combined Image" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
